spring:
  application:
    name: 智能创作平台
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/create_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 10
      max-active: 50
      min-idle: 20
      max-wait: 10000
      min-evictable-idle-time-millis: 300000
  redis:
    host: localhost
    port: 6379

server:
  port: 8888

mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl